### ISSUE TITLE
Check for duplicated emails and handle during signup in future

### ISSUE THREAD

**Issue by brooklynbagel** [leveler-dba/leveler#110]
I noticed some emails appear multiple timed. `src/components/SignUp/registration.js` should be verifying if an entry associate with an email already exists and if so either overwrite the details, error out or give the option some kind of prompt with options. 

What should we do with entries with duplicate emails?

- [ ] First step if entries with duplicated emails are same in other details, those are easy to clean-up.
- [ ] What to do if entries with duplicated emails differ (especially in `payment_url` field)? My instinct is to take the document with the most recent creation timestamp and keep that and discard the rest.

**Comment by adamcleavey** [comment]
https://bigcodenerd.org/enforce-cloud-firestore-unique-field-values/ this could work
