### ISSUE TITLE
Should emails be treated as case insensitive?

### ISSUE THREAD

**Issue by brooklynbagel** [leveler-dba/leveler#111]
See https://stackoverflow.com/a/9808332 for a case arguing they should be. Making emails case insensitive would simplify the admin panel and checking for duplicates (see issue #110).

**Comment by adamcleavey** [comment]
considering we don't need their email unless we're a) searching our DB for them in the admin, or b) sending them an email (which MailChimp handles anyway, out of our hands), i think we're safe to make them case insensitive.
