### ISSUE TITLE
database CRUD GUI?

### ISSUE THREAD

**Issue by sabinajuliya** [leveler-dba/leveler#49]
### User Story 

As a leveler admin I would like the ability to search, view, and edit user information, so that I may update emails, payment methods, and bios. 

### AC 

- search by email 
- can edit all submitted fields 
- can delete user 

### Notes

Open to whichever solution the team thinks is best!

**Comment by adamcleavey** [comment]
Here's my thought:

- leverage firebase authentication to have specific user restrictions on editing and deleting entries
- - username/password
- after that, search field for email of entry
- can edit any field, or delete the user.
