### ISSUE TITLE
Finalize Entry Data Model

### ISSUE THREAD

**Issue by samyoungnyc** [leveler-dba/leveler#5]
Define:

- keys **(Names)**
- values **Types**
- values **Optional vs. Required**

If any Personally-identifiable-information, how do we want to handle that?

Thus far we have:

**id:int 
timestamp 
email:string
city:string 
state:string 
industry:dict 
context:text 
payment_method:string 
payment_link:string 
social_handle:string 
suggestions:text**

**Comment by adamcleavey** [comment]
@samyoungnyc I suggest we generate region and send it in the payload rather than generate it in firebase, unless you think that's easier

**Comment by samyoungnyc** [comment]
@adamcleavey By payload, do you mean the JSON file we upload? Sorry I'm a bit unclear

**Comment by adamcleavey** [comment]
when we submit a form to firebase, we should find the region and include it in the payload, rather than calculating it on the server.

**Comment by samyoungnyc** [comment]
got it - so calculate region on the front-end before sending to DB right?
