### ISSUE TITLE
spike: venmo payment link issues

### ISSUE THREAD

**Issue by sabinajuliya** [leveler-dba/leveler#73]
as we chatted about during sprint planning there's an intermittent issue with some people's venmo payment links becoming appended to the end of the leveler url

**Comment by samyoungnyc** [comment]
hey @sabinajuliya - we made this issue 15 min ago - working on it - going to close this one bc the branch number is already #72 , so as not to cause confusion.

**Comment by samyoungnyc** [comment]
nevermind this is something else..

**Comment by samyoungnyc** [comment]
ok closing again lol - @brooklynbagel fixed this 2 days ago - we are working currently on making sure proper venmo links are supplied along with instructions in issue #72

**Comment by brooklynbagel** [comment]
This issue was opened up in issue #67 and has been fixed with the PR #69 in commit https://github.com/leveler-dba/leveler/pull/69/commits/9776f12a419c953e13d49b6c5c907dee6a80ff5f
