### ISSUE TITLE
Instructions Modal for incorrect Venmo and Paypal URLs

### ISSUE THREAD

**Issue by sabinajuliya** [leveler-dba/leveler#75]
#73 #74 

# User Story Venmo

As a user who has entered an incorrect venmo link and am shown an error, clicking onto instructions should display a modal with the below instructions. 

**Instructions Venmo** 

Do not enter a url containing your username! 

Open your venmo app, open the menu bar, and click onto your venmo code next to your profile picture. Click the “send” icon and then “copy” to copy your payment URL. Paste this url into the payment field we provide.  

This url will look something like https://venmo.com/code?user_id=12345678…

# User Story Paypal

As a user who has entered an incorrect paypal link and am shown an error, clicking onto instructions should display a modal with the below instructions. 

**Instructions PayPal**

If you do not already have a paypal.me link. Navigate to www.paypal.me and click get started to create your personal url. Please remember to post the full url, it needs to begin with “https://“ 

This url will look something like https://paypal.me/yourusername)

**Comment by brooklynbagel** [comment]
This makes sense to give the users some idea of what kind of URL they need to submit. 

Also just as a point I wouldn't push for forcing them to include the "https://" part - it's easy enough to correct for when the URL is incoming and most people are used to not including that in URLs.
