### ISSUE TITLE
Schedule daily backups of Firestore

### ISSUE THREAD

**Issue by brooklynbagel** [leveler-dba/leveler#97]
See https://firebase.google.com/docs/firestore/solutions/schedule-export for a guide on how to do it. May want to limit backups to some time interval (like 30 days) and see if they can be compressed.

**Comment by brooklynbagel** [comment]
Some questions to consider:
- Should a create a dedicated bucket for backups?
- Should backups be deleted after a period of time? (30 days?)
- Is it possible to not hard code in the project name for the bucket? (see https://googleapis.dev/nodejs/firestore/latest/v1.FirestoreAdminClient.html#getProjectId)

**Comment by adamcleavey** [comment]
thoughts:
1. yeah, a dedicated bucket is a good idea, we never know what needs we'll have later and it'll be good to have a dedicated backup we don't have to move or migrate.
2. 30 days seems sufficient. 30 days is the option they give for backing up the realtime database, so thats a good benchmark, even though I don't think we'd realistically use anything more than 7 days.
3. we can use the .env variables and set up the correct URL in the netlify config. that way the bucket name/address is still private.

**Comment by samyoungnyc** [comment]
@brooklynbagel Is this issue resolved?

**Comment by brooklynbagel** [comment]
@samyoungnyc Will a WIP. It looks like the automated backups are working but some things to address. @adamcleavey in response to your thoughts:

1. Will create a special bucket for backups and see if there's a way to have symlinks in buckets so there's a "latest" backup we can access more easily.
1. Will look into how to clear an item after 30 days.
1. Environment variables for Cloud Functions are separate from the Netlify variables, and we don't need to the the .env file tor that, see https://firebase.google.com/docs/functions/config-env
